// AUTO-GENERATED by shared/funnel-contract/generate.mjs — DO NOT EDIT BY HAND.
// Edit shared/funnel-contract/contract.mjs and re-run the generator.
// Consumed by the website (active-plus-website) via scripts/sync-funnel-contract.mjs.

export const FUNNEL_STEPS = [
  "welcome2",
  "gender",
  "dob",
  "socialProof",
  "aspiration",
  "activityLevel",
  "chairRise",
  "challengeArea",
  "standingComfort",
  "reinforcement2",
  "frequency",
  "bodyAreas",
  "planBuilding",
  "time",
  "register",
  "otp",
  "payment",
] as const;

export type FunnelStep = (typeof FUNNEL_STEPS)[number];

/** JSONB payload for merge_funnel_session / fill_missing_funnel_answers. Every key optional. */
export type QuestionnaireAnswers = Partial<{
  functionality_level: string; // Q1: fully_independent / balance_issues / chair_only
  functionality_path_followup: string; // Q2: per-path enum value (legacy; RPC v4 ignores)
  focus_areas: string[]; // Q3: balance / strength / flexibility / cardio
  daily_activity_level: string; // activityLevel: very_active / partially_active / mostly_sitting
  gender: string; // male / female
  pain_areas: string[]; // bodyAreas: knees / hips / lower_back / shoulders_neck / elbows / ankle / none
  pain_level: string; // LEGACY (painSeverity removed in v5 redesign; not collected)
  training_time_of_day: string; // Q8: HH:mm
  commitment_level: string; // Q9: urgent_now / important_to_start / evaluating (legacy; RPC v4 ignores)
  date_of_birth: string; // Screen 05: ISO-8601 date YYYY-MM-DD
  primary_motivation: string; // LEGACY (motivation removed in v5 redesign; not collected)
  single_leg_balance: string; // LEGACY (balance test removed in v5 redesign; not collected)
  chair_rise_capability: string; // chairRise (universal, influencing): alone / with_support / with_handles
  full_name: string; // Screen 020: free text → users.full_name
  training_frequency_choice: string; // frequency (4 opts): almost_daily / three_week / one_two_week / none → training_frequency int 6/3/2/0
  aspiration_goal: string; // aspiration (10-years): fitness / leisure / family / all (analytics only; RPC ignores)
  standing_stability: string; // standingComfort (assisted branch, influencing): stable / holds_support / seated — feeds derived functionality_level
  mobility_challenge: string; // challengeArea (independent branch): stairs / walking / floor_rise / none (analytics)
}>;

export const ANSWER_KEYS = ["functionality_level", "functionality_path_followup", "focus_areas", "daily_activity_level", "gender", "pain_areas", "pain_level", "training_time_of_day", "commitment_level", "date_of_birth", "primary_motivation", "single_leg_balance", "chair_rise_capability", "full_name", "training_frequency_choice", "aspiration_goal", "standing_stability", "mobility_challenge"] as const;

export const FUNCTIONALITY_PATHS = [
  { case: "independent", functionalityLevel: "fully_independent" },
  { case: "unstable", functionalityLevel: "balance_issues" },
  { case: "chair", functionalityLevel: "chair_only" },
] as const;
